apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  labels:
    app: {{ .Values.adService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adService.name }}
    spec:
      serviceAccountName: {{ .Values.adService.name }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.images.repository }}/{{ .Values.adService.name }}:{{ .Values.images.tag }}
        ports:
        - containerPort: 9555
        env:
          - name: PORT
            value: "9555"
        resources:
          {{- toYaml .Values.emailService.resources | nindent 10 }}
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adService.name }}
  labels:
    app: {{ .Values.adService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.adService.name }}
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adService.name }}
