apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 30080   # <-- YOUR fixed NodePort for HTTP
          - name: https
            port: 443
            targetPort: 8443
            nodePort: 30443   # <-- YOUR fixed NodePort for HTTPS
