apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service1-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/frontend-external"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: frontend-external
        port:
          number: 80
